// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfFgLsqSrgw7VCwnzd5auU4Q0h9blfPdo',
    appId: '1:859108089129:web:37a17f0f354788355f2b38',
    messagingSenderId: '859108089129',
    projectId: 'restaurant-4c8b6',
    authDomain: 'restaurant-4c8b6.firebaseapp.com',
    storageBucket: 'restaurant-4c8b6.firebasestorage.app',
    measurementId: 'G-KZEGV8Y13H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNTL2hOI2Nj-PHDOEMaf8SSOml23C6vw',
    appId: '1:859108089129:android:fef2244996006c8d5f2b38',
    messagingSenderId: '859108089129',
    projectId: 'restaurant-4c8b6',
    storageBucket: 'restaurant-4c8b6.firebasestorage.app',
  );

}